### ISSUE TITLE
RH above 100%

### ISSUE THREAD

**Issue by wxmanted** [wxstall/GridsSimp#20]
RH calculation crashed on Day 8.  It tried to put an RH above 100 percent. 

Probably need to clip values at 0 and 100.  But I'm wondering why it got a calculation above 100 in the first place. 
![lcarlaw_190303_812164275](https://user-images.githubusercontent.com/41652293/45115257-ec7edf00-b114-11e8-9e14-cd2d7fd29619.png)

**Comment by wxstall** [comment]
I haven't been able to replicate this yet. It's possible that a forecaster can do stuff in step 1, exit GridsSimp prior to the "finalize" stage, and then relaunch GridsSimp starting at step 2. This would mean T/Td checks (along with the other check/derive functions) would never get called. That's the only way I can envision this happening.

I may need to move the integrity checks to "pre step 2" instead of "post step 1", but need to make sure this won't break anything else first.

**Comment by wxstall** [comment]
I put in a check for "if RH >100, then RH =100", although it's still concerning that this occurred. Routine NDFD integrity checks should still alert the forecaster if Td exceeds T at any given hour.

**Comment by wxstall** [comment]
Cautiously will mark this fixed for 0.1.4
