### ISSUE TITLE
PoP & PoT & Wx Threshold

### ISSUE THREAD

**Issue by wxmanted** [wxstall/GridsSimp#8]
The PoP value to start making a PoTRainshowers is set to be 16 and greater.

The Wx value to make a SChc rain showers is set to be 15 and greater.   

So I had a Wx grid that made something cause the PoP was 15 in a spot even though the Pot grid didn't have something there.

Furthermore, how come the wx grid made something based off the PoP grid and not  PotRainshowers grid?  Does that seem right?  Shouldn't it always look at Pot grids?

**Comment by wxstall** [comment]
Fixed 0.1.2, will now use PoP >= 15 instead of PoP > 15  (threshold set by PoPlimiter config var).

The Wx grid has to use the PoP grid as a check. If someone has 60 PotShowers but only a 20 PoP, the PoP will limit the Wx grid to schc rather than likely's. The PoP will always drive the wx mention and the corresponding wording.
